trismegiste_oauth:
    resource: "@TrismegisteOAuthBundle/Resources/config/routing.xml"
    prefix:   /

trismegiste_front:
    resource: "@TrismegisteSocialBundle/Resources/config/routing.xml"
    prefix:   /

