security:
    encoders:
        Trismegiste\SocialBundle\Security\Netizen: sha1

    role_hierarchy:
        ROLE_USER:          ~
        ROLE_MODERATOR:     [ROLE_USER, ROLE_FREEPASS]
        ROLE_MANAGER:       [ROLE_MODERATOR, ROLE_FREEPASS]
        ROLE_ADMIN:         [ROLE_MANAGER, ROLE_FREEPASS, ROLE_PROMOTE]

    providers:
        proprietary:
            id: security.netizen.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            provider: proprietary
            stateless: false
            anonymous: ~
            oauth:
                login_path:   trismegiste_oauth_connect
                check_path:   trismegiste_oauth_check
                remember_me:  true
                success_handler: success_login_landing_page
                failure_handler: failure_login_not_registered
            remember_me:
                key: %secret%
                lifetime: 30000000
                path: /
                domain: ~
            logout:
                path:   trismegiste_oauth_logout
                target: /

    access_control:
        - { path: "^/admin/netizen/[0-9a-f]+/promote", roles: ROLE_ADMIN }
        - { path: ^/admin/config/, roles: ROLE_ADMIN }
        - { path: ^/admin/abusereport/, roles: ROLE_MODERATOR }
        - { path: ^/admin/, roles: ROLE_MANAGER }
        - { path: ^/registered/, roles: ROLE_USER }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sign, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: VALID_ACCESS }
