security:
    encoders:
        Trismegiste\SocialBundle\Security\Netizen: sha1

    role_hierarchy:
        ROLE_MODERATOR:     ROLE_USER
        ROLE_MARKETING:     ROLE_USER
        ROLE_ADMIN:         [ROLE_MODERATOR, ROLE_MARKETING]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        proprietary:
            id: security.netizen.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            provider: proprietary
            form_login:
                check_path: /login_check
                login_path: /guest/login
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/guest/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/abusereport/, roles: ROLE_MODERATOR }
        - { path: ^/admin/netizen/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
