security:
    encoders:
        Trismegiste\SocialBundle\Security\Netizen: sha1

    role_hierarchy:
        ROLE_USER:          ~
        ROLE_MODERATOR:     [ROLE_USER, ROLE_FREEPASS]
        ROLE_MANAGER:       [ROLE_MODERATOR, ROLE_FREEPASS]
        ROLE_ADMIN:         [ROLE_MANAGER, ROLE_FREEPASS, ROLE_PROMOTE]

    providers:
        proprietary:
            id: security.netizen.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            provider: proprietary
            form_login:
                check_path: trismegiste_logincheck
                login_path: trismegiste_login
                default_target_path: netizen_landing_page
                always_use_default_target_path: true
                csrf_provider: form.csrf_provider
            logout:
                path:   trismegiste_logout
                target: /
            anonymous: ~
            remember_me:
                key: %secret%
                lifetime: 30000000
                path: /
                domain: ~

    access_control:
        - { path: ^/admin/config/, roles: ROLE_ADMIN }
        - { path: ^/admin/abusereport/, roles: ROLE_MODERATOR }
        - { path: ^/admin/, roles: ROLE_MANAGER }
        - { path: ^/ticket/, roles: ROLE_USER }
        - { path: ^/afterlogin, roles: ROLE_USER }
        - { path: ^/guest/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: VALID_ACCESS }
